/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projmercearia;

/**
 *
 * @author anacl
 */
public class TelaVendas extends javax.swing.JFrame {
    FluxoVenda vendaAtual = new FluxoVenda(1, "28/06/2026");
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVendas.class.getName());

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoItem = new javax.swing.JTextField();
        txtQuantidadeItem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cboPagamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalGeral = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Código", "Produto", "Quantidade", "Preço Unit.", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tabelaItensVenda);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade:");

        txtCodigoItem.addActionListener(this::txtCodigoItemActionPerformed);

        txtQuantidadeItem.addActionListener(this::txtQuantidadeItemActionPerformed);

        jButton1.setText("Adicionar Item");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        cboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Pix" }));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Forma de Pagamento:");

        jButton2.setText("Finalizar Venda");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar Venda Comercial");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Geral:");

        txtTotalGeral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotalGeral.setText("R$ 0,00");
        txtTotalGeral.addActionListener(this::txtTotalGeralActionPerformed);

        jButton3.setText("Fechar Caixa");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeItemActionPerformed

    private void txtCodigoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoItemActionPerformed
    private double totalDaVendaAtual = 0.0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                       
        try {
        String codigoStr = txtCodigoItem.getText().trim();
        String qtdStr = txtQuantidadeItem.getText().trim();
        
        if (codigoStr.isEmpty() || qtdStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha o código e a quantidade!");
            return;
        }
        
        int codigoDigitado = Integer.parseInt(codigoStr);
        int qtdDesejada = Integer.parseInt(qtdStr);
        
        // Busca o produto real na tabela de 100 produtos do MySQL
        PainelControle controle = new PainelControle();
        Mercadoria m = controle.buscarMercadoriaPorCodigo(codigoDigitado);
        
        if (m != null) {
            String nomeReal = m.getNome();
            double precoReal = m.getPrecoVenda();
            double subtotalItem = precoReal * qtdDesejada;
            
            // Adiciona a linha perfeitamente na tabela do carrinho
            javax.swing.table.DefaultTableModel modeloVendas = (javax.swing.table.DefaultTableModel) tabelaItensVenda.getModel();
            modeloVendas.addRow(new Object[]{
                codigoDigitado, 
                nomeReal, 
                qtdDesejada, 
                "R$ " + precoReal, 
                "R$ " + subtotalItem
            });
            
            // Atualiza a matemática do total e joga na tela
            totalDaVendaAtual += subtotalItem;
            txtTotalGeral.setText(String.format("R$ %.2f", totalDaVendaAtual));
            
            // Limpa os campos para o próximo produto
            txtCodigoItem.setText("");
            txtQuantidadeItem.setText("1"); 
            txtCodigoItem.requestFocus();
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto com o código " + codigoDigitado + " não existe no banco!");
        }
        
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: Digite apenas números válidos.");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed
   private void atualizarTotalGeral() {
        javax.swing.table.DefaultTableModel modeloVendas = (javax.swing.table.DefaultTableModel) tabelaItensVenda.getModel();
        double totalGeral = 0.0;

        for (int i = 0; i < modeloVendas.getRowCount(); i++) {
            try {

                String qtdStr = modeloVendas.getValueAt(i, 2).toString().trim();
                int quantidade = Integer.parseInt(qtdStr);


                String precoStr = modeloVendas.getValueAt(i, 3).toString();
                precoStr = precoStr.replace("R$", "").replace(",", ".").trim();
                double precoUnitario = Double.parseDouble(precoStr);


                totalGeral += (quantidade * precoUnitario);

            } catch (Exception e) {
                System.out.println("Erro ao calcular linha " + i + ": " + e.getMessage());
            }
    }
    
    
    txtTotalGeral.setText(String.format("R$ %.2f", totalGeral));
}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (totalDaVendaAtual == 0.0) {
        javax.swing.JOptionPane.showMessageDialog(this, "O carrinho está vazio! Adicione itens antes de finalizar.");
        return;
        }

        String formaPagamento = cboPagamento.getSelectedItem().toString();

        
        String sqlVenda = "INSERT INTO venda_relatorio (total_venda, operador) VALUES (?, ?)";

        try (java.sql.Connection conn = ConexaoBanco.conectar();
             java.sql.PreparedStatement stmt = conn.prepareStatement(sqlVenda)) {

            stmt.setDouble(1, totalDaVendaAtual);
            stmt.setString(2, "Operador Caixa"); 
            stmt.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso via " + formaPagamento + "!");

           
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaItensVenda.getModel();
            modelo.setRowCount(0);
            totalDaVendaAtual = 0.0;
            txtTotalGeral.setText("R$ 0,00");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar venda no banco: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTotalGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalGeralActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String sqlSaida = "UPDATE historico_acesso SET hora_saida = CURTIME() "
                    + "WHERE data_acesso = CURDATE() AND hora_saida IS NULL";
    
        try (java.sql.Connection conn = ConexaoBanco.conectar();
             java.sql.PreparedStatement stmtSaida = conn.prepareStatement(sqlSaida)) {

            stmtSaida.executeUpdate();

        } catch (Exception e) {
            System.out.println("Erro ao registrar saída do operador: " + e.getMessage());
        }
       

       
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVendas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaItensVenda;
    private javax.swing.JTextField txtCodigoItem;
    private javax.swing.JTextField txtQuantidadeItem;
    private javax.swing.JTextField txtTotalGeral;
    // End of variables declaration//GEN-END:variables
}
